import { type Locale, i18n } from '@/i18n-config';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

interface IRootLayout {
  children: React.ReactNode;
  params: {
    lang: Locale;
  };
}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default async function RootLayout({ children, params }: IRootLayout) {
  return (
    <html lang={params.lang}>
      <body className={inter.className}>
        {children}
        {children}
      </body>
    </html>
  );
}
