import { getDictionary } from '@/common/helpers/get-dictionary';
import { type Locale, i18n } from '@/i18n-config';
import { Inter } from 'next/font/google';
import { NextIntlClientProvider } from 'next-intl';
import { type FC } from 'react';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

interface IRootLayout {
  children: React.ReactNode;
  params: {
    lang: Locale;
  };
}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

const RootLayout: FC<IRootLayout> = async ({ children, params }) => {
  const dictionary = await getDictionary(params.lang);

  return (
    <html lang={params.lang}>
      <body className={inter.className}>
        <NextIntlClientProvider locale={params.lang} messages={dictionary}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
};

export default RootLayout;
