import { THEME } from '@/common/interfaces/i-theme';
import { themeNameProperty } from '@/constans';
import { Inter } from 'next/font/google';
import { cookies } from 'next/headers';
import { NextIntlClientProvider } from 'next-intl';
import { type FC } from 'react';
import './globals.scss';

const inter = Inter({ subsets: ['latin'] });

interface IParams {
  locale: string;
}

interface IRootLayout {
  children: React.ReactNode;
  params: IParams;
}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: FC<IRootLayout> = async ({ children, params }) => {
  const messages = (await import(`../../../messages/${params.locale}.json`)).default;
  const theme = cookies().get(themeNameProperty)?.value ?? THEME.dark;

  return (
    <html lang={params.locale} className={theme}>
      <body className={inter.className}>
        <NextIntlClientProvider locale={params.locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
};

export default RootLayout;
